[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "wibt-tool"
version = "0.1.0"
description = "Science in Understandable Language tool"
requires-python = ">=3.10"
dependencies = [
  "python-dotenv",
  "requests",
  "openai",
  "marimo",
  "altair",
  "pandas",
  "pyarrow",
  "pydantic",
  "matplotlib",
  "plotly",
  "docling"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.marimo.runtime]
pythonpath = ["src"]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
]
